version: '3.4'

services:
  acc-text-api:
    build:
      context: .
      dockerfile: api/Dockerfile
  gf:
    build:
      context: ./core/gf
  front-end:
    build:
      context: .
      dockerfile: front-end/Dockerfile
      args:
        ACC_TEXT_API_URL: "http://localhost:3001"
        ACC_TEXT_GRAPHQL_URL: "http://localhost:3001/_graphql"
        DATA_FILES_BUCKET: "http://localhost:3001/accelerated-text-data-files"
