site_name: Accelerated Text
site_url: https://www.acceleratedtext.com/
repo_url: https://github.com/tokenmill/accelerated-text/
edit_uri: tree/master/docs
site_description: "Data to text platform to generate natural language descriptions of your data"

nav:
    - Introduction: index.md
    - Getting Started:
        - Platform: platform.md
        - Installation: installation.md
        - First Steps: first-steps.md
        - Adding AMRs: amr.md
        - Conditionals: conditionals.md
        - Creating a dictionary: dictionary.md
        - Adding operations: operations.md
        - Selecting languages: languages.md
        - Exporting data: export.md
    - Advanced Topics:
        - Blocks: blocks.md
        - Deployment: deployment.md
        - NLG API: nlg-api.md
        - GraphQL API: graphql.md
    - Contributing: contributing.md
markdown_extensions:
    - toc
    - tables
    - meta
plugins:
    - search
theme: readthedocs
copyright: Copyright &copy; 2019 <a href="https://www.tokenmill.ai/">TokenMill UAB</a>.
